version: '3'

services:

    php_sbs:
        user: 1000:1000
        build:
            context: .
            dockerfile: ./app/Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        container_name: php_sbs_container
        volumes:
            - ./app:/app
        env_file:
            - ./app/.env.local
        command: ["rr", "serve", "-c", ".rr.dev.yaml"]
        ports:
            - "8080:8080"

    mysql8_sbs:
        image: mysql:8
        container_name: mysql8_sbs_container
        ports:
            - "4306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret

    phpmyadmin_sbs:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_sbs_container
        environment:
            PMA_HOST: mysql8_sbs
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "7080:80"
        depends_on:
            - mysql8_sbs

volumes:
    mysql_sbs:
